baseURL = 'https://www.0xnullifier.xyz'
theme = "hugo-bearblog"
enableRobotsTXT = true
title = "0xnullifier"
disableKinds = ["taxonomy", "404", "term"]


[params]

author = "0xnullifier"


[[params.navlinks]]
name = "blogs/"
url = "blogs/"
title = "My Blogs"
[[params.navlinks]]
name = "github"
url = "https://github.com/0xnullifier"
title = "Github"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = true
